CREATE TABLE [dbo].[Person]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY(1, 1),
	[PersonId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_dbo_Person_PersonId DEFAULT NEWID(),
	[FirstName] VARCHAR(50) NOT NULL,
	[LastName] VARCHAR(50) NOT NULL,
	[Address] VARCHAR(100) NOT NULL,
	[City] VARCHAR(50) NOT NULL,
	[State] CHAR(2) NOT NULL,
	[Zip] CHAR(5) NOT NULL,
	[Phone] VARCHAR(10) NOT NULL,
	[Email] VARCHAR(100) NULL,
	[VersionUser] VARCHAR(50) NOT NULL CONSTRAINT DF_dbo_Person_VersionUser DEFAULT SYSTEM_USER,
	[VersionDate] DATETIME NOT NULL CONSTRAINT DF_dbo_Person_VersionDate DEFAULT GETDATE(),
	[DeletedDate] DATETIME NULL,
	[CreatedUser] VARCHAR(50) NOT NULL CONSTRAINT DF_dbo_Person_CreatedUser DEFAULT SYSTEM_USER,
	[CreatedDate] DATETIME NOT NULL CONSTRAINT DF_dbo_Person_CreatedDate DEFAULT GETDATE()
)